# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bitcoin Design
email: no-reply@bitcoindesign.org
description: "Bitcoin Design is a free open-source community resource that helps designers and developers working on bitcoin-products to create better experiences, faster."
# baseurl: "Guide" # Only for gh-pages. Comment this line to run the website on localhost:4000
url: "https://bitcoin.design" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

github_repository_url: "https://github.com/BitcoinDesign/Guide/"
slack_invite_url: "https://join.slack.com/t/bitcoindesign/shared_invite/zt-1rxp55chx-dH6pWlTtWBqRw7VztgvBGA"
discord_invite_url: "https://discord.gg/K7aQ5PErht"
youtube_url: "https://www.youtube.com/c/BitcoinDesign"
twitter_url: "https://twitter.com/bitcoin_design"
nostr_url: "https://nosta.me/_@bitcoin.design"
bitcoin_tv_url: "https://bitcointv.com/c/bitcoindesign/videos"

# Build settings
theme: minima
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

imageoptim:
  allow_lossy: true
  skip_missing_workers: true
  pngout: false
  verbose: false
  svgo: false

compress_images:
  images_path: "assets/**/*.{gif,png,jpg,jpeg}"

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: ":path/:basename"
      image: "https://bitcoin.design/assets/images/bitcoin-design-preview.jpg"


twitter:
  username: bitcoin_design
  card: summary

social:
  name: Bitcoin Design
  links:
    github: bitcoindesign
    slack: bitcoindesign
    discord: bitcoindesign

exclude:
  - README.md
  - _compress_images_cache.yml

include:
- .well-known

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
